version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: language_learning_db_solo
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: language_learning
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
